version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_TCP_PORT=${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}

  api:
    container_name: api
    image: spring-boot-api
    build: api/.
    env_file: ./.env
    ports:
      - ${API_PORT}:${API_PORT}
      - "5005:5005"
    depends_on:
      - mysql
    environment:
      - spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
      - spring.datasource.url=jdbc:mysql://mysql:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
      - spring.datasource.username=${DB_USER}
      - spring.datasource.password=${DB_PASSWORD}
      - spring.jpa.hibernate.ddl-auto=validate
      - spring.liquibase.change-log=classpath:db.changelog/db.changelog-master.yaml

  frontend:
    container_name: frontend
    image: frontend
    build: frontend/.
    ports:
      - "4200:4200"
    depends_on:
      - api
    volumes:
      - ./frontend:/usr/src/app:delegated
      - /usr/src/app/node_modules
      - /usr/src/app/.angular
